# Generated by Django 5.2 on 2025-04-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0003_rename_dungeonsanddragons5echaracter_dungeonsanddragonsfiftheditioncharacter",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="level",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
