# Generated by Django 5.2 on 2025-04-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_dungeonsanddragonsfiftheditionitem_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DungeonsAndDragonsFifthEditionItem",
        ),
    ]
