# Generated by Django 5.2 on 2025-04-24 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_dungeonsanddragonsfiftheditionitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            old_name="characterClass",
            new_name="character_class",
        ),
        migrations.CreateModel(
            name="DungeonsAndDragonsFifthEditionAbilityScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("score", models.PositiveIntegerField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.dungeonsanddragonsfiftheditioncharacter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DungeonsAndDragonsFifthEditionSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=10000)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.dungeonsanddragonsfiftheditioncharacter",
                    ),
                ),
            ],
        ),
    ]
