# Generated by Django 5.2 on 2025-04-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0008_rename_characterclass_dungeonsanddragonsfiftheditioncharacter_character_class_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="DungeonsAndDragonsFifthEditionSkill",
        ),
    ]
