# Generated by Django 5.2 on 2025-04-24 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_delete_dungeonsanddragonsfiftheditionskill"),
    ]

    operations = [
        migrations.CreateModel(
            name="DungeonsAndDragonsFifthEditionSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("proficiency", models.PositiveIntegerField()),
                (
                    "ability_score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.dungeonsanddragonsfiftheditionabilityscore",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.dungeonsanddragonsfiftheditioncharacter",
                    ),
                ),
            ],
        ),
    ]
