# Generated by Django 5.2 on 2025-04-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_dungeonsanddragonsfiftheditionskill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dungeonsanddragonsfiftheditionabilityscore",
            name="score",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="level",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="dungeonsanddragonsfiftheditionskill",
            name="proficiency",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
