# Generated by Django 5.2 on 2025-04-24 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0011_alter_dungeonsanddragonsfiftheditionabilityscore_score_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DungeonsAndDragonsFifthEditionAttack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("attack_bonus", models.IntegerField(default=0)),
                ("damage_amount", models.CharField(max_length=200)),
                ("damage_type", models.CharField(max_length=200)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.dungeonsanddragonsfiftheditioncharacter",
                    ),
                ),
            ],
        ),
    ]
