# Generated by Django 5.2 on 2025-04-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_dungeonsanddragonsfiftheditioncharacter_hp_current_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="armor_class",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
