# Generated by Django 5.2 on 2025-04-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_dungeonsanddragonsfiftheditioncharacter_armor_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditionattack",
            name="notes",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditionattack",
            name="range",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditionitem",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditionitem",
            name="weight",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dungeonsanddragonsfiftheditionattack",
            name="damage_type",
            field=models.CharField(default="", max_length=200),
        ),
    ]
