# Generated by Django 5.2 on 2025-05-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_dungeonsanddragonsfiftheditionattack_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditionabilityscore",
            name="saving_throw",
            field=models.BooleanField(default=False),
        ),
    ]
