# Generated by Django 5.2 on 2025-05-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0017_rename_damage_amount_dungeonsanddragonsfiftheditionattack_damage_roll",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dungeonsanddragonsfiftheditionattack",
            name="attack_bonus",
            field=models.CharField(max_length=200),
        ),
    ]
