# Generated by Django 5.2 on 2025-05-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_dungeonsanddragonsfiftheditionattack_attack_bonus"),
    ]

    operations = [
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spellcasting_ability_score",
            field=models.CharField(default="", max_length=200),
        ),
    ]
