# Generated by Django 5.2 on 2025-05-02 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0019_dungeonsanddragonsfiftheditioncharacter_spellcasting_ability_score",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            old_name="spellcasting_ability_score",
            new_name="spellcasting_ability",
        ),
    ]
