# Generated by Django 5.2 on 2025-05-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0020_rename_spellcasting_ability_score_dungeonsanddragonsfiftheditioncharacter_spellcasting_ability",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level1_current",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level1_maximum",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level2_current",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level2_maximum",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level3_current",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level3_maximum",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level4_current",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level4_maximum",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level5_current",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level5_maximum",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level6_current",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level6_maximum",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level7_current",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level7_maximum",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level8_current",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level8_maximum",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level9_current",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="spell_slots_level9_maximum",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
