# Generated by Django 5.2 on 2025-05-02 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0021_dungeonsanddragonsfiftheditioncharacter_spell_slots_level1_current_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DungeonsAndDragonsFifthEditionSpell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("level", models.PositiveIntegerField(default=0)),
                ("description", models.CharField(max_length=10000)),
                ("school", models.CharField(max_length=200)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.dungeonsanddragonsfiftheditioncharacter",
                    ),
                ),
            ],
        ),
    ]
