# Generated by Django 5.2 on 2025-05-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_dungeonsanddragonsfiftheditionspell"),
    ]

    operations = [
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="coins_copper",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="coins_electrum",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="coins_gold",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="coins_platinum",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="coins_silver",
            field=models.IntegerField(default=0),
        ),
    ]
