# Generated by Django 5.2 on 2025-05-02 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_dungeonsanddragonsfiftheditioncharacter_coins_copper_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="description_personality",
            field=models.CharField(default="", max_length=20000),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="description_physical",
            field=models.CharField(default="", max_length=20000),
        ),
        migrations.AddField(
            model_name="dungeonsanddragonsfiftheditioncharacter",
            name="proficiencies",
            field=models.CharField(default="", max_length=20000),
        ),
        migrations.AlterField(
            model_name="dungeonsanddragonsfiftheditionitem",
            name="description",
            field=models.CharField(default="", max_length=10000),
        ),
        migrations.CreateModel(
            name="DungeonsAndDragonsFifthEditionFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=20000)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.dungeonsanddragonsfiftheditioncharacter",
                    ),
                ),
            ],
        ),
    ]
