# Generated by Django 5.2 on 2025-05-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0024_dungeonsanddragonsfiftheditioncharacter_description_personality_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DungeonsAndDragonsFifthEditionFeature",
            new_name="DungeonsAndDragonsFifthEditionTrait",
        ),
    ]
