# Generated by Django 5.2 on 2025-05-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_alter_dungeonsanddragonsfiftheditionskill_proficiency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dungeonsanddragonsfiftheditionitem",
            name="weight",
            field=models.CharField(default="", max_length=200),
        ),
    ]
